### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by FranklinYu** [niligulmohar/pyenv-rpm#1]
Hi, is this project still maintained?

**Comment by niligulmohar** [comment]
Hi!

Sporadically. I still use it myself. I never made builds for the latest Fedora releases since the COPR repository for earlier releases still worked for me.

I'm missing the later python versions from `python-build` so i'm probably making a new release soon.

**Comment by FranklinYu** [comment]
Hi, `python-build` is missing in the `pyenv` package. I verified this with package from

https://copr-be.cloud.fedoraproject.org/results/nili/pyenv/fedora-29-x86_64/00838280-pyenv/pyenv-1.2.8-1.fc29.noarch.rpm

**Comment by niligulmohar** [comment]
Hi!

There is a separate pyenv-python-build package for that.

Maybe it should be a recommended dependency for the pyenv package, or just included in pyenv? I made it separate because of its much larger dependencies.

**Comment by FranklinYu** [comment]
@niligulmohar Thanks. I missed that somehow. It makes sense to be another gem because `python-build` can actually work without `pyenv`.

**Comment by niligulmohar** [comment]
Pyenv now recommends the other packages :white_check_mark:
